-- MARK AT ZERO
-- Phase C: precomputed mosaic tile metadata
--
-- Stores metadata for generated mosaic tile images.
-- The actual tile images will live in object storage / CDN.
-- This table does not modify individual Marks.

create table if not exists public.mosaic_tiles (
  id bigint generated by default as identity primary key,

  level integer not null,
  tile_x integer not null,
  tile_y integer not null,

  west double precision not null,
  east double precision not null,
  south double precision not null,
  north double precision not null,

  image_url text not null,

  mark_count bigint not null default 0,

  version bigint not null default 1,

  status text not null default 'ready'
    check (status in ('pending', 'ready', 'dirty', 'failed')),

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint mosaic_tiles_level_position_unique
    unique (level, tile_x, tile_y),

  constraint mosaic_tiles_longitude_bounds
    check (
      west >= -180
      and east <= 180
      and west < east
    ),

  constraint mosaic_tiles_latitude_bounds
    check (
      south >= -85.05112878
      and north <= 85.05112878
      and south < north
    ),

  constraint mosaic_tiles_level_valid
    check (level >= 0),

  constraint mosaic_tiles_position_valid
    check (tile_x >= 0 and tile_y >= 0),

  constraint mosaic_tiles_mark_count_valid
    check (mark_count >= 0),

  constraint mosaic_tiles_version_valid
    check (version >= 1)
);

create index if not exists mosaic_tiles_level_status_idx
  on public.mosaic_tiles (level, status);

create index if not exists mosaic_tiles_bounds_idx
  on public.mosaic_tiles (
    level,
    west,
    east,
    south,
    north
  );